apiVersion: v1
kind: Service
metadata:
  labels:
    app: shop-p254
  name: shop-p254
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: shop-p254
status:
  loadBalancer: {}
