ARG UBUNTU_VERSION=22.04

FROM ubuntu:${UBUNTU_VERSION}

RUN apt-get update && apt-get install -y curl lsb-release nginx

ARG UBUNTU_VERSION

RUN echo "현재 빌드에 사용된 ubuntu version: ${UBUNTU_VERSION}"

LABEL maintainer="himang10@gmail.com"

LABEL description="SKALA Linux Version"

EXPOSE 8080/tcp
EXPOSE 80/tcp

# nginx 기본 웹루트로 이동 후 index.html 복사 (default.conf 수정 없이 index.html만 교체)
WORKDIR /var/www/html
COPY index.html .

# skala 그룹 및 사용자 추가
RUN groupadd skala && \
    useradd -m -s /bin/bash -g skala skala

# skala 사용자로 전환
# 이후 CMD는 skala 권한으로 실행되며, 아래 두 가지 이유로 권한 오류 발생:
# skala는 80번 포트(privileged port < 1024) 바인딩 불가
USER skala

CMD ["nginx", "-g", "daemon off;"]
