spring:
  application:
    name: myapp
  profiles:
    active: local
  lifecycle:
    timeout-per-shutdown-phase: 20s # graceful shutdown 최대 대기 시간

server:
  shutdown: graceful # SIGTERM 수신 시 진행 중인 요청을 마무리하고 종료

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
  show-actuator: false

management:
  server:
    port: 8080 # Actuator 포트 설정
  endpoints:
    web:
      exposure:
        include: "*" # Prometheus endpoint 노출
  endpoint:
    health:
      show-details: always # Health endpoint 상세 정보 노출
      probes:
        enabled: true # LivenessState, ReadinessState 활성화
      group:
        readiness:
          include: readinessState,myService  # readiness에 myService 포함
        liveness:
          include: livenessState # liveness는 기본만 포함
  health:
    livenessState:
      enabled: true # LivenessState 활성화
    readinessState:
      enabled: true # ReadinessState 활성화
  metrics:
    enable:
      all: true # 모든 기본 메트릭 활성화


logging:
  level:
    '[com.sk.skala.myapp.controller]': DEBUG
    '[com.sk.skala.myapp.service]': DEBUG